apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lantern
resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - middleware.yaml
  - ingress.yaml
images:
  - name: ghcr.io/askolesov/lantern
    newTag: v0.1.0
