apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lantern-content
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-storage
  volumeName: lantern-content
  resources:
    requests:
      storage: 50Gi
