#!/usr/bin/env python3
"""Split src/condensed.json (written by condense.py) into per-chapter story packages:
  NN/node.yaml (only created if missing, so `hidden:` edits survive), NN/text.json, NN/scenes.json,
  NN/cover.jpg (copied from the first scene if missing). Run from the package dir
  (lantern-content/books/hobbit). The scene order/captions used to live in build.py."""
import json, os, pathlib, shutil
scenes={
0:[('bagend','Дом Бильбо'), ('gandalf_meets_bilbo','Доброе утро!'), ('dwalin_arrives','Двалин, к твоим услугам'), ('balin_tea','Балин за чаем'), ('fili_kili_crowd','Гномы всё прибывают'), ('thorin_arrives','Торин Дубощит'), ('feast_table','Пир в норке'), ('washing_up_song','Бей, ломай!'), ('misty_mountains_song','Далеко за туманные горы'), ('tookish_stirring','Туковская жилка'), ('bilbo_faints','Обморок Бильбо'), ('bilbo_declares_burglar','Я и есть взломщик'), ('map_and_dragon','Карта и ключ'), ('bedtime','Бильбо засыпает')],
1:[('bilbo_oversleeps','Гномы ушли без него'), ('running_to_inn','Бегом, без шляпы'), ('meeting_at_inn','У Зелёного Дракона'), ('riding_out','В путь, майским утром'), ('rain_and_wilderland','Дождь в Пустоши'), ('camp_no_gandalf','Пони в реке'), ('distant_fire','Огонёк в лесу'), ('bilbo_scouts_trolls','Три тролля у костра'), ('bilbo_caught','Взлохоббит!'), ('dwarves_ambushed','Мешок за мешком'), ('thorin_fights','Торин бьётся'), ('trolls_bicker','Голоса из темноты'), ('trolls_turn_to_stone','Рассвет их застиг'), ('troll_cave_treasure','Пещера троллей')],
2:[('riding_toward_mountains','Горы впереди'), ('gandalf_leads','Гэндальф ищет тропу'), ('valley_descent','Спуск в долину'), ('elves_singing','Песня эльфов на деревьях'), ('rivendell_welcome','Добро пожаловать в долину'), ('elves_teasing_feast','Смех эльфов за столом'), ('last_homely_house','Последний Домашний Приют'), ('elrond_portrait','Элронд рассматривает мечи'), ('moon_letters','Лунные буквы'), ('durins_day','День Дурина'), ('midsummer_morning','Ясное утро отправления')],
3:[('climbing_ponies','Вверх в горы на пони'),('storm_giants','Гроза и каменные великаны'),('cave_smoke_rings','Колечки дыма в пещере'),('crack_opens','Стена раскрылась'),('goblin_hall','Зал гоблинов'),('orcrist_revealed','Великий Гоблин узнал меч'),('glamdring_strike','Меч в темноте'),('running_tunnels','Бегство по туннелям'),('two_swords_corner','Гэндальф и Торин у поворота'),('dori_grabbed','Бильбо упал')],
4:[('finds_ring','Кольцо в темноте'),('gollum_lake','Голлум на озере'),('riddle_game','Игра в загадки'),('fish_jumps','Рыба!'),('pocket_question','Что у меня в кармане?'),('three_guesses','Три попытки'),('lost_precious','Пропало!'),('gollum_blocks','Голлум у выхода'),('the_leap','Прыжок'),('stuck_in_door','Застрял в двери'),('buttons_fly','Пуговицы врассыпную')],
5:[('balin_watch','Балин в дозоре'),('burglar_appears','А вот и взломщик!'),('scree_slide','Вниз по осыпи'),('dwarves_in_trees','Гномы на деревьях'),('dori_lifts_bilbo','Дори выручает'),('fire_cones','Горящие шишки'),('goblin_fire_song','Песня гоблинов'),('eagle_snatches_gandalf','Орёл спасает Гэндальфа'),('hanging_from_dori','На ножках Дори'),('eagle_lord_talks','Повелитель орлов'),('ledge_supper','Ужин на уступе')],
6:[('eagle_ride','На спине орла'),('bee_meadow','Пчёлы Беорна'),('beorn_axe','Беорн'),('dwarves_by_twos','Гномы по двое'),('bombur_last','Бомбур последний'),('animal_servants','Слуги-животные'),('night_growl','Ночной рык'),('beorn_warning','Совет Беорна'),('riding_bear_follows','Медведь следом'),('ponies_home','Пони уходят домой'),('gandalf_farewell','Не сходите с тропинки!')],
7:[('eyes_in_dark','Глаза в темноте'),('deer_leap','Олень'),('butterflies','Чёрные бабочки'),('elf_feast','Пир эльфов'),('elvenking_feast','Король эльфов'),('bilbo_vs_spider','Бильбо и паук'),('cocoons','Гномы в коконах'),('stones_and_song','Камни и дразнилка'),('battle_under_tree','Битва с пауками'),('bilbo_vanishes','Бильбо исчезает'),('thorin_before_king','Торин у короля'),('thorin_cell','Торин в темнице')],
8:[('bridge_gate','Через мост'),('balin_before_king','Балин и Король'),('keyhole','Через замочную скважину'),('cellar_trapdoor','Погреб и люк'),('keys','Ключи'),('thorin_freed','Торин на свободе'),('into_barrels','В бочки!'),('last_barrel','Последняя бочка'),('riding_barrel','Верхом на бочке'),('bilbo_sneeze','Апчхи!'),('raft_dawn','Плот на рассвете')],
# ch.10 re-planned 2026-09-16 against the condensed text (old 14-slot list above was against the pre-condense
# full text, now stale); pictures generated and contact-sheet checked the same day.
9:[('mountain_sighted','Одинокая Гора вдали'),('long_lake','Долгое озеро'),('laketown','Эсгарот'),('bilbo_frees_thorin','Бильбо открывает бочку'),('dwarves_ashore','Гномы на берегу'),('thorin_at_the_hut','Торин у сторожки'),('thorin_in_the_hall','Торин в зале'),('town_sings','Город поёт'),('thorin_enthroned','Торин на почётном месте'),('bilbo_sick','Бильбо простудился'),('departure','Отплытие к Горе')],
# ch.11-12 planned and pictures generated 2026-09-16, contact-sheet checked.
10:[('company_departs','В путь к Горе'),('desolation_march','Драконова Пустошь'),('scouting_gate','Разведка у Ворот'),('map_by_firelight','Карта у костра'),('finding_the_door','Дверь найдена'),('hauling_up_ropes','Подъём на верёвках'),('bilbo_on_the_doorstep','Бильбо на крылечке'),('dwarves_grumble','Гномы ворчат'),('thrush_and_door','Дрозд и дверь')],
11:[('thorin_sends_bilbo','Торин отправляет Бильбо'),('bilbo_descends','Спуск во тьму'),('tunnel_glow','Отсвет впереди'),('smaug_hoard','Смауг на золоте'),('bilbo_steals_cup','Бильбо крадёт чашу'),('smaug_bursts_out','Смауг вырывается наружу'),('rope_rescue','Спасение на верёвках'),('second_descent_eye','Красный глаз из-под века'),('riddle_names','Загадочные имена'),('barrel_rider_taunt','Наездник Бочки'),('smaug_revenge_roar','Месть! - рёв дракона'),('diamond_waistcoat','Алмазный жилет'),('bilbo_burnt_escape','Бегство от огня'),('thrush_listens','Дрозд слушает'),('smaug_flies_to_lake','Смауг летит к Озеру')],
# ch.13-19 planned 2026-09-16 against the condensed text; STUB images (placeholder art) until real pictures are generated.
12:[('door_blocked','Дверь завалена'), ('into_the_dark','Все вместе вниз'), ('bilbo_finds_arkenstone','Аркенстон'), ('bilbo_pockets_stone','Тайком в карман'), ('bat_scare','Летучая мышь'), ('gold_fever','Золотая лихорадка'), ('mithril_coat','Мифриловая кольчуга'), ('front_gate_daylight','К свету'), ('ravenhill_camp','Сторожевой пост')],
13:[('town_sees_light','Свет на Горе'), ('dragon_attacks','Атака дракона'), ('town_burns','Город горит'), ('bard_last_arrow','Последняя стрела'), ('black_arrow_strike','Чёрная стрела'), ('smaug_falls','Смауг падает'), ('survivors_mourn','Уцелевшие на берегу'), ('elves_march_to_lake','Эльфы спешат к озеру')],
14:[('watching_birds','Птицы над Горой'), ('old_thrush_returns','Старый дрозд'), ('roac_arrives','Роак, сын Карка'), ('treasure_now_ours','Смауг мёртв!'), ('gate_wall_built','Новая стена'), ('distant_campfires','Костры в долине'), ('armies_arrive','Войско у пруда'), ('dwarves_song','Песня гномов'), ('bard_parley','Переговоры у пруда'), ('herald_demand','Требование глашатая'), ('thorin_shoots_arrow','Стрела в щит')],
15:[('arkenstone_hidden','Поиски камня'), ('bombur_watch','Дозор Бомбура'), ('bilbo_slips_away','Бильбо уходит'), ('river_stumble','Бильбо в реке'), ('elves_capture','Эльфы находят хоббита'), ('arkenstone_reveal','Камень на свету'), ('gandalf_reappears','Гэндальф снова здесь'), ('bilbo_climbs_back','Обратно на стену')],
16:[('bard_delegation','Посольство у стены'), ('arkenstone_ultimatum','Аркенстон открыт'), ('torin_grabs_bilbo','Гнев Торина'), ('gandalf_intervenes','Гэндальф вмешивается'), ('ransom_offer','Выкуп за камень'), ('dain_army_arrives','Войско Даина'), ('dain_standoff','Даин у переправы'), ('storm_and_bats','Гроза и тьма'), ('gandalf_warns','Гоблины идут!'), ('battle_valley','Битва в долине'), ('thorin_bursts_out','Торин выходит из ворот'), ('eagles_arrive','Орлы!')],
17:[('bilbo_wakes_alone','Один на скале'), ('soldier_finds_bilbo','Хоббита нашли'), ('carried_to_camp','Несут в лагерь'), ('gandalf_reunion','Встреча с Гэндальфом'), ('thorin_farewell','Прощание с Торином'), ('beorn_rescue','Спасение Беорна'), ('treasure_farewell_gifts','Дары Барда'), ('dwarves_goodbye','Прощание с гномами'), ('journey_with_beorn','В пути с Беорном'), ('beorns_house_winter','Зима у Беорна')],
18:[('rivendell_return','Снова Ривенделл'), ('elrond_fireside_tale','Рассказ у камина'), ('moonlit_lullaby','Колыбельная эльфов'), ('troll_gold_dig','Клад троллей'), ('homeward_road','Дорога домой'), ('bilbo_sees_the_hill','Родная Горка'), ('auction_chaos','Аукцион'), ('home_at_last','Дома, много лет спустя'), ('balin_visits','Визит Балина')],

}

chs = json.load(open("src/condensed.json"))
for i, ch in enumerate(chs):
    d = pathlib.Path(f"{i+1:02d}"); d.mkdir(exist_ok=True); (d / "img").mkdir(exist_ok=True)
    json.dump(ch["paras"], open(d / "text.json", "w"), ensure_ascii=False, indent=0)
    sc = [{"img": f, "caption": c} for f, c in scenes.get(i, [])]
    json.dump(sc, open(d / "scenes.json", "w"), ensure_ascii=False, indent=0)
    if not (d / "node.yaml").exists():
        (d / "node.yaml").write_text(f'type: story\ntitle: {ch["title"]}\nlabel: {ch["num"]}\ntext: text.json\nscenes: scenes.json\nimages: img\n')
    first = d / "img" / (sc[0]["img"] + ".jpg") if sc else None
    if first and first.exists() and not (d / "cover.jpg").exists():
        shutil.copy(first, d / "cover.jpg")
    print(d, ch["num"], ch["title"], len(ch["paras"]), "paras", len(sc), "scenes", "" if first and first.exists() else "(no pictures)")
