# (chapter, slug, english prompt, russian caption) — in story order
S = {
4: [
 ("path_up","A small company on ponies climbing a narrow zigzag path up into huge grey mountains, tiny against the peaks.","Вверх в горы"),
 ("looking_back","Bilbo on a pony looking back at a green land far below, the Shire tiny in the distance, mountains all around.","Оглядываясь назад"),
 ("storm","A wild thunderstorm in the mountains at night, lightning over the peaks, tiny travelers huddling under a ledge.","Гроза в горах"),
 ("stone_giants","Huge stone giants tossing boulders to each other across a mountain valley in a storm, lightning, dwarves watching in awe.","Каменные великаны"),
 ("cave_found","Two dwarves peering into a dry cave mouth in a cliff, holding a lantern, rain pouring outside.","Пещера"),
 ("cave_sleep","Dwarves, Gandalf, Bilbo and ponies asleep in a dry cave, a small fire glowing, cozy despite the storm.","Ночлег в пещере"),
 ("crack_opens","A crack opening in the back wall of a cave, many goblin hands and eyes reaching out, Bilbo waking with a shout.","Стена раскрылась"),
 ("gandalf_flash","A big bright flash of blue-white light in a dark cave, goblins tumbling back, Gandalf's shape in the light.","Вспышка Гэндальфа"),
 ("goblin_tunnels","Small goblins with lanterns hurrying dwarves in a line through rough dark tunnels, downhill, funny and grumpy.","Гоблины ведут в туннели"),
 ("goblin_hall","A huge underground hall with red firelight, goblins crowding around, dwarves in a row, the Great Goblin on a big stone seat.","Большой зал гоблинов"),
 ("great_goblin","The Great Goblin, a huge round goblin with a big head and crown, shouting from his throne, small goblins cheering.","Великий Гоблин"),
 ("sword_glow","A goblin holding up an old elvish sword that glows with cold blue light, goblins around shrinking away in fear.","Меч засветился"),
 ("lights_out","Total darkness in a big hall, only a glowing sword and a wizard's staff visible, goblins running everywhere.","Свет погас"),
 ("running_tunnels","Dwarves running through a dark tunnel carrying Bilbo on their backs, a glowing sword lighting the way, goblins far behind.","Бегство по туннелям"),
 ("dori_grabbed","A goblin grabbing a dwarf's leg from behind in a dark tunnel, a little hobbit tumbling off his shoulders into the dark.","Бильбо упал"),
],
5: [
 ("alone_dark","Bilbo the hobbit alone in complete darkness in a tunnel, only his face faintly lit, looking around, scared but brave.","Один в темноте"),
 ("finds_ring","Bilbo's hand touching a small gold ring on the floor of a dark tunnel, the ring glinting.","Кольцо"),
 ("pipe_dark","Bilbo sitting in the dark tunnel trying to find his pipe and matches, small comfort.","Трубка в кармане"),
 ("small_sword","Bilbo drawing a small elvish dagger that glows faintly blue, lighting the tunnel walls.","Маленький меч светится"),
 ("walking_down","Bilbo walking carefully down a long dark tunnel, one hand on the wall, glowing dagger in the other.","Вниз по туннелю"),
 ("underground_lake","A wide dark underground lake, still black water, a faint light, a tiny figure at the shore.","Подземное озеро"),
 ("gollum_boat","Gollum, a small pale thin creature with big round pale glowing eyes, paddling a tiny boat silently on a dark lake.","Голлум в лодочке"),
 ("gollum_eyes","Two big pale lamp-like eyes glowing in the darkness over black water, Bilbo holding up his dagger.","Глаза в темноте"),
 ("gollum_meets","Gollum crouching on a rock talking to Bilbo, both curious and wary, Bilbo holding his little glowing sword.","Знакомство"),
 ("riddle_mountain","A dreamy picture of a mountain with roots deep in the earth, taller than trees, illustrating a riddle.","Загадка о горе"),
 ("riddle_teeth","A dreamy picture of a row of white horses on a red hill, illustrating the riddle about teeth.","Загадка о зубах"),
 ("gollum_thinks","Gollum scratching his head thinking hard, eyes narrowed, Bilbo waiting on a rock by the water.","Голлум думает"),
 ("riddle_wind","Swirling wind blowing through a cave, illustrating the riddle about wind, leaves flying.","Загадка о ветре"),
 ("riddle_sun","Golden sun rays shining over a meadow of daisies, illustrating the riddle about the sun.","Загадка о солнце"),
 ("riddle_dark","A drawing of darkness filling a hole, stars around, illustrating the riddle about dark.","Загадка о тьме"),
 ("riddle_egg","A shiny white egg in a nest with a golden glow, illustrating the riddle about eggs.","Загадка о яйце"),
 ("riddle_fish","A silver fish swimming in a cold dark stream, illustrating the riddle about fish.","Загадка о рыбе"),
 ("riddle_time","An old clock, a crumbling mountain and a fallen tree, illustrating the riddle about time, dreamlike.","Загадка о времени"),
 ("pocket_question","Bilbo with his hand in his pocket asking a question, Gollum confused and counting on his fingers.","Что у меня в кармане?"),
 ("gollum_island","Gollum on a small rocky island in the dark lake, searching frantically among stones, hissing.","Голлум ищет на острове"),
 ("gollum_angry","Gollum with angry glowing eyes paddling fast toward the shore, Bilbo backing away.","Голлум рассердился"),
 ("ring_on","Bilbo slipping the gold ring on his finger and turning half-transparent, Gollum running right past him.","Кольцо на пальце"),
 ("following_gollum","Invisible Bilbo (faintly outlined) following Gollum up a dark tunnel, Gollum sniffing the air.","Следом за Голлумом"),
 ("gollum_blocks","Gollum crouched at a tunnel exit, blocking it, whispering, a faint light beyond.","Голлум у выхода"),
 ("the_leap","Bilbo leaping high over Gollum's head in a tunnel, coat flying, toward a light.","Прыжок"),
 ("back_door","Bilbo squeezing through a big stone door with goblin guards nearby, daylight and trees outside.","Задняя дверь"),
 ("outside","Bilbo alone in sunshine on a mountainside, trees, valley below, catching his breath, very relieved.","Наружу!"),
],
6: [
 ("bilbo_sunshine","Bilbo sitting on a rock in the sun looking over pine forests and a valley, the mountains behind him.","На солнце"),
 ("hears_voices","Bilbo hiding behind a tree listening to dwarves and Gandalf arguing in a dell below.","Голоса в лощине"),
 ("bilbo_appears","Bilbo suddenly stepping out among the surprised dwarves, Gandalf laughing, Balin the lookout astonished.","Бильбо появился"),
 ("telling_story","Bilbo telling his story to a circle of dwarves, arms wide, dwarves listening open-mouthed.","Рассказ Бильбо"),
 ("gandalf_story","Gandalf telling how he escaped the goblins, dwarves around, mountains behind.","Рассказ Гэндальфа"),
 ("down_slope","Dwarves and a hobbit scrambling down a steep slope of loose stones, a landslide of pebbles, pine trees below.","Вниз по осыпи"),
 ("pine_forest","A dark pine forest in the evening, the company walking on a soft carpet of needles, worried looks.","Сосновый лес"),
 ("wolf_howl","Dwarves and Bilbo stopping to listen, a wolf howl in the distance, moonlit hillside, pine trees.","Вой волков"),
 ("up_trees","Dwarves scrambling up pine trees, Bilbo hanging from a low branch, a dwarf pulling him up.","На деревья!"),
 ("wargs_circle","A ring of big grey wolves (wargs) sitting under pine trees in moonlight, howling at the moon, dwarves in the branches above.","Варги в лесу"),
 ("gandalf_firecones","Gandalf up a tree throwing blazing pine cones in blue, green and red flames at wolves below, wolves yelping.","Горящие шишки"),
 ("wolves_run","Wolves running with tails on fire through the trees, flames catching in the grass.","Волки бегут"),
 ("goblins_come","Goblins arriving in the moonlit clearing laughing at the burning trees, wolves circling again.","Пришли гоблины"),
 ("goblin_song","Goblins dancing in a ring around burning trees, singing, dwarves clinging to branches above.","Песня гоблинов"),
 ("eagles_arrive","Great golden eagles swooping down over a burning forest at night, wings wide, moonlight.","Орлы!"),
 ("eagle_lord","The huge Lord of the Eagles with a stern noble face, perched on a rocky ledge, watching.","Повелитель орлов"),
 ("carried","Bilbo dangling from an eagle's talons high over a forest, terrified and amazed, stars above.","В когтях орла"),
 ("eyrie","A high rocky ledge in the mountains, dwarves and Bilbo waking up, eagles' nests, dawn.","Орлиное гнездо"),
 ("eagle_fire","Eagles bringing sticks and rabbits, dwarves roasting meat on a small fire on a mountain ledge.","Ужин на скале"),
 ("eagle_flight","Fifteen great eagles flying in the morning sky carrying dwarves, mountains and rivers far below.","Полёт"),
 ("carrock","Eagles landing on a great rock in a river (the Carrock), dwarves climbing off, river shining.","Каррок"),
 ("farewell_eagles","Eagles soaring away into the sunrise, dwarves waving from a rock in the river.","Прощание с орлами"),
],
7: [
 ("carrock_morning","Dwarves and Bilbo at the top of a great rock in a river, sun rising, a ford below, a long green land ahead.","Утро на Карроке"),
 ("gandalf_warns","Gandalf talking seriously to dwarves on the rock, pointing across the river toward distant oak woods.","Гэндальф предупреждает"),
 ("crossing_ford","Dwarves wading across a shallow ford, Bilbo carried on a dwarf's shoulders, water sparkling.","Через брод"),
 ("bee_pastures","Huge bees humming over meadows of clover and flowers, the company walking through tall grass.","Пчелиные луга"),
 ("great_oaks","A row of ancient tall oak trees, a high thorn hedge, a wooden gate, Gandalf and Bilbo approaching.","Дубы и изгородь"),
 ("beorn_garden","A wide garden with beehives shaped like little houses, flowers, a long low wooden house, horses looking over a fence.","Сад Беорна"),
 ("beorn","Beorn, a huge man with a thick black beard and hair, bare arms, leaning on an axe, kind but stern face.","Беорн"),
 ("beorn_listens","Beorn sitting on a bench listening to Gandalf's story, dwarves arriving two by two through the gate.","Беорн слушает"),
 ("dwarves_pairs","Pairs of dwarves bowing at a garden gate, one after another, Beorn amused, Gandalf pretending surprise.","Гномы по двое"),
 ("beorn_hall","A great wooden hall with a fire in the middle, pillars like tree trunks, smoke going up to a hole in the roof.","Дом Беорна"),
 ("animal_servants","Ponies and big dogs walking on hind legs carrying torches, setting a long table with dishes, sheep bringing bread.","Слуги-животные"),
 ("feast_beorn","A supper of honey, cream, nuts and bread in a great hall, dwarves eating happily, Beorn at the head of the table.","Ужин у Беорна"),
 ("beorn_stories","Beorn telling stories by the fire, dwarves listening, big dogs lying around, shadows dancing.","Рассказы у огня"),
 ("night_growl","Bilbo awake at night in a wooden hall hearing a growl outside, moonlight through the door, a big shadow.","Ночной рык"),
 ("bear_tracks","Big bear paw prints in soft earth near a garden, Gandalf examining them, morning.","Медвежьи следы"),
 ("gandalf_gone","Dwarves and Bilbo alone in a big hall, Gandalf's seat empty, lots of food on the table.","Гэндальф ушёл"),
 ("bilbo_worries","Bilbo lying on a bench worrying, hands behind head, a dog sleeping nearby.","Бильбо тревожится"),
 ("gandalf_returns","Gandalf returning at evening through the gate, tired, dwarves rushing to meet him.","Гэндальф вернулся"),
 ("bear_moot","Many bears of all sizes gathered in a moonlit meadow far away, dancing in a ring (seen from a distance, dreamlike).","Медвежий совет"),
 ("beorn_returns","Beorn returning cheerfully, laughing, holding a goblin cap and a wolf skin, dwarves relieved.","Беорн вернулся"),
 ("beorn_advice","Beorn pointing at a map spread on the table, warning about a dark forest, dwarves attentive.","Совет Беорна"),
 ("ponies_loaded","Dwarves loading Beorn's ponies with food bags and water skins, Beorn watching, morning.","Пони в дорогу"),
 ("riding_north","The company riding fast on ponies across grassland toward a dark line of trees, a great bear following far behind.","На север"),
 ("mirkwood_edge","The edge of a huge dark forest, trees like a black wall, a company on ponies small in front of it.","Опушка Лихолесья"),
 ("gandalf_farewell","Gandalf on his horse waving goodbye at the forest edge, dwarves sad, Bilbo very sad.","Прощание с Гэндальфом"),
 ("ponies_home","Ponies trotting back home across the grass without riders, dwarves watching them go.","Пони уходят домой"),
 ("into_forest","Dwarves and a hobbit walking into a dark forest tunnel of trees, last daylight behind them.","В лес"),
],
8: [
 ("dark_path","A narrow path through a gloomy forest, trees twisted, cobwebs, greenish twilight, tiny travelers.","Тропа в темноте"),
 ("forest_eyes","Many pairs of eyes glowing among dark trees at night, a small campfire, dwarves huddled close.","Глаза в лесу"),
 ("black_squirrels","Black squirrels and big moths fluttering around the travelers, gloomy forest, Bilbo swatting.","Чёрные белки"),
 ("black_stream","A black stream crossing the path in a dark forest, a small boat on the far bank, dwarves peering at it.","Чёрный ручей"),
 ("rope_boat","Fili throwing a rope with a hook toward a boat across a dark stream, dwarves watching.","Лодка на верёвке"),
 ("deer_leap","A white deer leaping over a black stream in a dark forest, a dwarf falling into the water.","Олень"),
 ("bombur_sleeps","A fat dwarf being carried asleep on a stretcher by the others through a forest, smiling in his sleep.","Бомбур спит"),
 ("bilbo_tree","Bilbo climbing high up a tree, his head popping out above a sea of green leaves, sun and butterflies.","Над листвой"),
 ("butterflies","Black butterflies fluttering around a hobbit's head above a green treetop sea, blue sky.","Бабочки"),
 ("no_end","Bilbo looking sadly at endless treetops in every direction, no end to the forest.","Лесу нет конца"),
 ("hungry_camp","Dwarves sitting glumly around an empty bag, hungry, dark forest, Bombur waking up.","Голодная стоянка"),
 ("far_lights","Twinkling lights and laughter among distant trees at night, dwarves peeking through bushes.","Огоньки в лесу"),
 ("elf_feast","Elves feasting under trees by firelight, lanterns, food and music, seen through leaves.","Пир эльфов"),
 ("lights_vanish","Fire and lights vanishing suddenly, dwarves stumbling in the dark, calling to each other.","Огни погасли"),
 ("thorin_falls","Thorin stepping into a ring of light and falling asleep under a spell, elves staring.","Торин заснул"),
 ("bilbo_alone_wood","Bilbo alone in the pitch-dark forest, hand on a tree, listening.","Один в лесу"),
 ("spider_thread","Sticky spider threads wrapping around a hobbit's legs, a big spider creeping close in the dark.","Паучья нить"),
 ("bilbo_fights","Bilbo striking a giant spider with his small glowing sword, the spider backing off.","Бильбо сражается"),
 ("sting","Bilbo proudly holding up his little sword and naming it, standing over a fallen spider, forest gloom.","Жало"),
 ("spider_colony","Many giant spiders hanging in a dark clearing full of thick webs, bundles hanging from branches.","Гнездо пауков"),
 ("dwarves_wrapped","Dwarves wrapped in cocoons of spider silk hanging from branches, only their beards and noses showing.","Гномы в коконах"),
 ("bilbo_stones","Bilbo throwing stones at spiders from behind a tree, one spider tumbling off a branch.","Камни в пауков"),
 ("bilbo_song","Invisible Bilbo singing a teasing song, spiders rushing angrily in the wrong direction.","Дразнилка"),
 ("cutting_free","Bilbo cutting cocoons open with his sword, a dwarf tumbling out, other dwarves waking up.","Освобождение"),
 ("spider_battle","Dwarves with sticks and Bilbo with a sword fighting off giant spiders in a clearing, webs everywhere.","Битва с пауками"),
 ("escape_spiders","Dwarves and Bilbo stumbling out of the spider clearing exhausted, spiders giving up behind.","Спаслись"),
 ("ring_secret","Dwarves looking at Bilbo with new respect while he shyly shows the little gold ring.","Секрет кольца"),
 ("elves_capture","Wood-elves with bows and lanterns surrounding sleepy dwarves in the forest, torches.","Лесные эльфы"),
 ("thorin_king","Thorin standing before the Elvenking in a great underground hall, the king on a wooden throne with a leaf crown.","Торин у короля"),
 ("thorin_cell","Thorin sitting in a stone cell with bread and water, thinking stubbornly.","Торин в темнице"),
],
9: [
 ("elf_line","Dwarves blindfolded being led in a line by elves across a bridge over a dark river into a cave-palace.","Через мост"),
 ("elvenking_hall","A great hall carved in rock, pillars like tree trunks, the Elvenking on his throne with a crown of berries and leaves.","Зал Короля эльфов"),
 ("questioning","The Elvenking questioning stubborn dwarves, elves with spears, dwarves scowling.","Допрос"),
 ("dwarves_cells","Dwarves locked in separate stone cells in a corridor lit by torches, an elf guard walking past.","Гномы в темнице"),
 ("bilbo_invisible","Invisible Bilbo (faint outline) creeping past elf guards in a torchlit corridor.","Бильбо-невидимка"),
 ("bilbo_finds_thorin","Bilbo whispering through the keyhole of a cell door, Thorin's surprised eye at the hole.","Нашёл Торина"),
 ("wine_cellar","Elves rolling big barrels in a stone cellar, a trapdoor over rushing dark water.","Винный погреб"),
 ("guards_drink","Two elf guards and a butler dozing at a table with empty cups, keys on a belt, candle burning.","Стражники уснули"),
 ("keys","Bilbo carefully lifting a bunch of keys from a sleeping elf's belt, holding his breath.","Ключи"),
 ("unlocking","Bilbo unlocking cell doors one by one, dwarves creeping out into the corridor.","Открываем двери"),
 ("into_barrels","Dwarves climbing into empty barrels, Bilbo packing straw around them, one dwarf's feet sticking out.","В бочки!"),
 ("bombur_barrel","A fat dwarf squeezed into a barrel, only his nose showing, Bilbo pushing the lid on.","Бомбур в бочке"),
 ("trapdoor","Elves lifting a trapdoor and rolling barrels down into rushing dark water.","Люк открыт"),
 ("bilbo_jump","Bilbo leaping onto the last barrel as it falls through the trapdoor into the water.","Прыжок в воду"),
 ("river_barrels","Barrels bobbing down a fast forest river, Bilbo clinging to one, wet and cold.","По реке"),
 ("raft_elves","Elves on the riverbank tying barrels together into a raft with poles, lanterns.","Плот из бочек"),
 ("forest_ends","The river coming out of the dark forest into open marshland, sky wide, a distant lonely mountain.","Лес кончился"),
 ("mountain_view","A lonely mountain far away across a lake in evening light, Bilbo on a barrel staring at it.","Гора вдали"),
 ("laketown_far","A wooden town on stilts far out on a lake, lights twinkling, evening, barrel raft approaching.","Озёрный город"),
 ("bilbo_cold","Bilbo on a barrel at night shivering and sneezing, wrapped in his coat, stars above.","Холодная ночь"),
],
10: [
 ("long_lake","A wide lake with a great mountain rising beyond, the river flowing in, autumn light.","Долгое озеро"),
 ("laketown","A wooden town built on stilts over a lake, bridges and boats, wooden houses, smoke from chimneys.","Эсгарот"),
 ("barrels_shore","Barrels pushed onto a shallow shore by elves with poles, a small cabin nearby, dawn.","Бочки на берегу"),
 ("bilbo_opens","Bilbo prying open a barrel with a knife, a soggy dwarf (Thorin) climbing out stiffly.","Бильбо открывает бочки"),
 ("wet_dwarves","Thirteen wet, bruised, grumpy dwarves standing on a shore dripping, Bilbo apologetic.","Мокрые гномы"),
 ("bridge_guards","Thorin and dwarves marching onto a wooden bridge, town guards jumping up in surprise.","Стража у моста"),
 ("master_feast","A great hall in a wooden town, the fat Master at a long table, Thorin announcing himself, elves at the table looking shocked.","Пир у Бургомистра"),
 ("town_cheers","Crowds of townspeople cheering on wooden bridges and boats, dwarves waving, lanterns.","Город ликует"),
 ("old_songs","Townspeople singing old songs about the King under the Mountain, children dancing on the quay.","Старые песни"),
 ("dwarves_fine","Dwarves in fine new clothes with combed beards, looking very important in a town street.","Новые наряды"),
 ("bilbo_cold_town","Bilbo with a red nose and a blanket, sneezing, in a warm wooden room, tea nearby.","Бильбо простудился"),
 ("boats_loaded","Big boats being loaded with supplies and ponies on a lake shore, dwarves supervising.","Лодки готовы"),
 ("departure","Boats rowing away up the lake toward the mountain, townspeople waving from the quay, autumn.","Отплытие"),
 ("mountain_ahead","A boat on a grey lake, the lonely mountain looming ahead under cloudy sky, Bilbo looking worried.","К Горе"),
],
}
